### PR TITLE
Update workflow.yaml

### PR DESCRIPTION
**Pull request by smorimoto**

### CODE REVIEW

**Comment by smorimoto** [comment]
This allows you to automatically test the latest version every week.

**Comment by smorimoto** [comment]
To make testing a little easier, we have provided a test action for the asdf plugin, but there are still some issues and it doesn't work in some environments. Try it if you are interested. By the way, you don't need to write the uninstall command except in special cases.
https://github.com/asdf-vm/actions

**Comment by gr1m0h** [comment]
> To make testing a little easier, we have provided a test action for the asdf plugin, but there are still some issues and it doesn't work in some environments. Try it if you are interested. By the way, you don't need to write the uninstall command except in special cases.
> https://github.com/asdf-vm/actions

Thank you.
I will check it.

**Comment by gr1m0h** [comment]
Thank you for your contribution.
Looks good to me.

**Pull request merged**
