### PR TITLE
Support Graviton instances / Amazon Linux 2

### PR DESCRIPTION
**Pull request by offbyone**

### CODE REVIEW

**Comment by offbyone** [comment]
If this repo is inactive, would you be okay if I proposed my fork as a default source for asdf-vm's plugin list?

**Comment by gr1m0h** [comment]
> If this repo is inactive, would you be okay if I proposed my fork as a default source for asdf-vm's plugin list?

Why do you think inactive?
It just doesn't have the necessary updates. This repo is active.

**Comment by offbyone** [comment]
Nope, just checking. Is there anything. you would need in order to merge this?

**Comment by gr1m0h** [comment]
This PR is not a problem.
Thank you.

**Pull request merged**
